DROP TABLE if EXISTS users;

CREATE TABLE users(
    id SERIAL PRIMARY key,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    pwd VARCHAR(255) NOT NULL,
    bio VARCHAR(1000),
    profile_pic VARCHAR(1000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
